/*
Bitly API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.0
Contact: api@bitly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Tags struct for Tags
type Tags struct {
	Tags *[]string `json:"tags,omitempty"`
}

// NewTags instantiates a new Tags object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTags() *Tags {
	this := Tags{}
	return &this
}

// NewTagsWithDefaults instantiates a new Tags object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagsWithDefaults() *Tags {
	this := Tags{}
	return &this
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *Tags) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tags) GetTagsOk() (*[]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *Tags) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *Tags) SetTags(v []string) {
	o.Tags = &v
}

func (o Tags) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	return json.Marshal(toSerialize)
}

type NullableTags struct {
	value *Tags
	isSet bool
}

func (v NullableTags) Get() *Tags {
	return v.value
}

func (v *NullableTags) Set(val *Tags) {
	v.value = val
	v.isSet = true
}

func (v NullableTags) IsSet() bool {
	return v.isSet
}

func (v *NullableTags) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTags(val *Tags) *NullableTags {
	return &NullableTags{value: val, isSet: true}
}

func (v NullableTags) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTags) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
