/*
Bitly API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.0
Contact: api@bitly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// BulkShortenValidate struct for BulkShortenValidate
type BulkShortenValidate struct {
	GroupGuid    *string `json:"group_guid,omitempty"`
	Email        *string `json:"email,omitempty"`
	CustomDomain *string `json:"custom_domain,omitempty"`
	Filename     string  `json:"filename"`
}

// NewBulkShortenValidate instantiates a new BulkShortenValidate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkShortenValidate(filename string) *BulkShortenValidate {
	this := BulkShortenValidate{}
	this.Filename = filename
	return &this
}

// NewBulkShortenValidateWithDefaults instantiates a new BulkShortenValidate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkShortenValidateWithDefaults() *BulkShortenValidate {
	this := BulkShortenValidate{}
	return &this
}

// GetGroupGuid returns the GroupGuid field value if set, zero value otherwise.
func (o *BulkShortenValidate) GetGroupGuid() string {
	if o == nil || o.GroupGuid == nil {
		var ret string
		return ret
	}
	return *o.GroupGuid
}

// GetGroupGuidOk returns a tuple with the GroupGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkShortenValidate) GetGroupGuidOk() (*string, bool) {
	if o == nil || o.GroupGuid == nil {
		return nil, false
	}
	return o.GroupGuid, true
}

// HasGroupGuid returns a boolean if a field has been set.
func (o *BulkShortenValidate) HasGroupGuid() bool {
	if o != nil && o.GroupGuid != nil {
		return true
	}

	return false
}

// SetGroupGuid gets a reference to the given string and assigns it to the GroupGuid field.
func (o *BulkShortenValidate) SetGroupGuid(v string) {
	o.GroupGuid = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *BulkShortenValidate) GetEmail() string {
	if o == nil || o.Email == nil {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkShortenValidate) GetEmailOk() (*string, bool) {
	if o == nil || o.Email == nil {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *BulkShortenValidate) HasEmail() bool {
	if o != nil && o.Email != nil {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *BulkShortenValidate) SetEmail(v string) {
	o.Email = &v
}

// GetCustomDomain returns the CustomDomain field value if set, zero value otherwise.
func (o *BulkShortenValidate) GetCustomDomain() string {
	if o == nil || o.CustomDomain == nil {
		var ret string
		return ret
	}
	return *o.CustomDomain
}

// GetCustomDomainOk returns a tuple with the CustomDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkShortenValidate) GetCustomDomainOk() (*string, bool) {
	if o == nil || o.CustomDomain == nil {
		return nil, false
	}
	return o.CustomDomain, true
}

// HasCustomDomain returns a boolean if a field has been set.
func (o *BulkShortenValidate) HasCustomDomain() bool {
	if o != nil && o.CustomDomain != nil {
		return true
	}

	return false
}

// SetCustomDomain gets a reference to the given string and assigns it to the CustomDomain field.
func (o *BulkShortenValidate) SetCustomDomain(v string) {
	o.CustomDomain = &v
}

// GetFilename returns the Filename field value
func (o *BulkShortenValidate) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *BulkShortenValidate) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *BulkShortenValidate) SetFilename(v string) {
	o.Filename = v
}

func (o BulkShortenValidate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.GroupGuid != nil {
		toSerialize["group_guid"] = o.GroupGuid
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.CustomDomain != nil {
		toSerialize["custom_domain"] = o.CustomDomain
	}
	if true {
		toSerialize["filename"] = o.Filename
	}
	return json.Marshal(toSerialize)
}

type NullableBulkShortenValidate struct {
	value *BulkShortenValidate
	isSet bool
}

func (v NullableBulkShortenValidate) Get() *BulkShortenValidate {
	return v.value
}

func (v *NullableBulkShortenValidate) Set(val *BulkShortenValidate) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkShortenValidate) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkShortenValidate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkShortenValidate(val *BulkShortenValidate) *NullableBulkShortenValidate {
	return &NullableBulkShortenValidate{value: val, isSet: true}
}

func (v NullableBulkShortenValidate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkShortenValidate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
