/*
Bitly API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.0
Contact: api@bitly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SSOVerifySlug struct for SSOVerifySlug
type SSOVerifySlug struct {
	Available *bool   `json:"available,omitempty"`
	UrlSlug   *string `json:"url_slug,omitempty"`
}

// NewSSOVerifySlug instantiates a new SSOVerifySlug object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSSOVerifySlug() *SSOVerifySlug {
	this := SSOVerifySlug{}
	return &this
}

// NewSSOVerifySlugWithDefaults instantiates a new SSOVerifySlug object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSSOVerifySlugWithDefaults() *SSOVerifySlug {
	this := SSOVerifySlug{}
	return &this
}

// GetAvailable returns the Available field value if set, zero value otherwise.
func (o *SSOVerifySlug) GetAvailable() bool {
	if o == nil || o.Available == nil {
		var ret bool
		return ret
	}
	return *o.Available
}

// GetAvailableOk returns a tuple with the Available field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SSOVerifySlug) GetAvailableOk() (*bool, bool) {
	if o == nil || o.Available == nil {
		return nil, false
	}
	return o.Available, true
}

// HasAvailable returns a boolean if a field has been set.
func (o *SSOVerifySlug) HasAvailable() bool {
	if o != nil && o.Available != nil {
		return true
	}

	return false
}

// SetAvailable gets a reference to the given bool and assigns it to the Available field.
func (o *SSOVerifySlug) SetAvailable(v bool) {
	o.Available = &v
}

// GetUrlSlug returns the UrlSlug field value if set, zero value otherwise.
func (o *SSOVerifySlug) GetUrlSlug() string {
	if o == nil || o.UrlSlug == nil {
		var ret string
		return ret
	}
	return *o.UrlSlug
}

// GetUrlSlugOk returns a tuple with the UrlSlug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SSOVerifySlug) GetUrlSlugOk() (*string, bool) {
	if o == nil || o.UrlSlug == nil {
		return nil, false
	}
	return o.UrlSlug, true
}

// HasUrlSlug returns a boolean if a field has been set.
func (o *SSOVerifySlug) HasUrlSlug() bool {
	if o != nil && o.UrlSlug != nil {
		return true
	}

	return false
}

// SetUrlSlug gets a reference to the given string and assigns it to the UrlSlug field.
func (o *SSOVerifySlug) SetUrlSlug(v string) {
	o.UrlSlug = &v
}

func (o SSOVerifySlug) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Available != nil {
		toSerialize["available"] = o.Available
	}
	if o.UrlSlug != nil {
		toSerialize["url_slug"] = o.UrlSlug
	}
	return json.Marshal(toSerialize)
}

type NullableSSOVerifySlug struct {
	value *SSOVerifySlug
	isSet bool
}

func (v NullableSSOVerifySlug) Get() *SSOVerifySlug {
	return v.value
}

func (v *NullableSSOVerifySlug) Set(val *SSOVerifySlug) {
	v.value = val
	v.isSet = true
}

func (v NullableSSOVerifySlug) IsSet() bool {
	return v.isSet
}

func (v *NullableSSOVerifySlug) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSSOVerifySlug(val *SSOVerifySlug) *NullableSSOVerifySlug {
	return &NullableSSOVerifySlug{value: val, isSet: true}
}

func (v NullableSSOVerifySlug) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSSOVerifySlug) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
