/*
Bitly API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.0
Contact: api@bitly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CampaignClicksData struct for CampaignClicksData
type CampaignClicksData struct {
	CreatedTs        *int32                   `json:"created_ts,omitempty"`
	Description      *string                  `json:"description,omitempty"`
	BrandGuid        *string                  `json:"brand_guid,omitempty"`
	CampaignChannels *[]CampaignChannelClicks `json:"campaign_channels,omitempty"`
	CreatedBy        *string                  `json:"created_by,omitempty"`
	ModifiedTs       *int32                   `json:"modified_ts,omitempty"`
	TotalClicks      *int32                   `json:"total_clicks,omitempty"`
	Guid             *string                  `json:"guid,omitempty"`
	Name             *string                  `json:"name,omitempty"`
}

// NewCampaignClicksData instantiates a new CampaignClicksData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignClicksData() *CampaignClicksData {
	this := CampaignClicksData{}
	return &this
}

// NewCampaignClicksDataWithDefaults instantiates a new CampaignClicksData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignClicksDataWithDefaults() *CampaignClicksData {
	this := CampaignClicksData{}
	return &this
}

// GetCreatedTs returns the CreatedTs field value if set, zero value otherwise.
func (o *CampaignClicksData) GetCreatedTs() int32 {
	if o == nil || o.CreatedTs == nil {
		var ret int32
		return ret
	}
	return *o.CreatedTs
}

// GetCreatedTsOk returns a tuple with the CreatedTs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignClicksData) GetCreatedTsOk() (*int32, bool) {
	if o == nil || o.CreatedTs == nil {
		return nil, false
	}
	return o.CreatedTs, true
}

// HasCreatedTs returns a boolean if a field has been set.
func (o *CampaignClicksData) HasCreatedTs() bool {
	if o != nil && o.CreatedTs != nil {
		return true
	}

	return false
}

// SetCreatedTs gets a reference to the given int32 and assigns it to the CreatedTs field.
func (o *CampaignClicksData) SetCreatedTs(v int32) {
	o.CreatedTs = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CampaignClicksData) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignClicksData) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CampaignClicksData) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CampaignClicksData) SetDescription(v string) {
	o.Description = &v
}

// GetBrandGuid returns the BrandGuid field value if set, zero value otherwise.
func (o *CampaignClicksData) GetBrandGuid() string {
	if o == nil || o.BrandGuid == nil {
		var ret string
		return ret
	}
	return *o.BrandGuid
}

// GetBrandGuidOk returns a tuple with the BrandGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignClicksData) GetBrandGuidOk() (*string, bool) {
	if o == nil || o.BrandGuid == nil {
		return nil, false
	}
	return o.BrandGuid, true
}

// HasBrandGuid returns a boolean if a field has been set.
func (o *CampaignClicksData) HasBrandGuid() bool {
	if o != nil && o.BrandGuid != nil {
		return true
	}

	return false
}

// SetBrandGuid gets a reference to the given string and assigns it to the BrandGuid field.
func (o *CampaignClicksData) SetBrandGuid(v string) {
	o.BrandGuid = &v
}

// GetCampaignChannels returns the CampaignChannels field value if set, zero value otherwise.
func (o *CampaignClicksData) GetCampaignChannels() []CampaignChannelClicks {
	if o == nil || o.CampaignChannels == nil {
		var ret []CampaignChannelClicks
		return ret
	}
	return *o.CampaignChannels
}

// GetCampaignChannelsOk returns a tuple with the CampaignChannels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignClicksData) GetCampaignChannelsOk() (*[]CampaignChannelClicks, bool) {
	if o == nil || o.CampaignChannels == nil {
		return nil, false
	}
	return o.CampaignChannels, true
}

// HasCampaignChannels returns a boolean if a field has been set.
func (o *CampaignClicksData) HasCampaignChannels() bool {
	if o != nil && o.CampaignChannels != nil {
		return true
	}

	return false
}

// SetCampaignChannels gets a reference to the given []CampaignChannelClicks and assigns it to the CampaignChannels field.
func (o *CampaignClicksData) SetCampaignChannels(v []CampaignChannelClicks) {
	o.CampaignChannels = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *CampaignClicksData) GetCreatedBy() string {
	if o == nil || o.CreatedBy == nil {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignClicksData) GetCreatedByOk() (*string, bool) {
	if o == nil || o.CreatedBy == nil {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *CampaignClicksData) HasCreatedBy() bool {
	if o != nil && o.CreatedBy != nil {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *CampaignClicksData) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetModifiedTs returns the ModifiedTs field value if set, zero value otherwise.
func (o *CampaignClicksData) GetModifiedTs() int32 {
	if o == nil || o.ModifiedTs == nil {
		var ret int32
		return ret
	}
	return *o.ModifiedTs
}

// GetModifiedTsOk returns a tuple with the ModifiedTs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignClicksData) GetModifiedTsOk() (*int32, bool) {
	if o == nil || o.ModifiedTs == nil {
		return nil, false
	}
	return o.ModifiedTs, true
}

// HasModifiedTs returns a boolean if a field has been set.
func (o *CampaignClicksData) HasModifiedTs() bool {
	if o != nil && o.ModifiedTs != nil {
		return true
	}

	return false
}

// SetModifiedTs gets a reference to the given int32 and assigns it to the ModifiedTs field.
func (o *CampaignClicksData) SetModifiedTs(v int32) {
	o.ModifiedTs = &v
}

// GetTotalClicks returns the TotalClicks field value if set, zero value otherwise.
func (o *CampaignClicksData) GetTotalClicks() int32 {
	if o == nil || o.TotalClicks == nil {
		var ret int32
		return ret
	}
	return *o.TotalClicks
}

// GetTotalClicksOk returns a tuple with the TotalClicks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignClicksData) GetTotalClicksOk() (*int32, bool) {
	if o == nil || o.TotalClicks == nil {
		return nil, false
	}
	return o.TotalClicks, true
}

// HasTotalClicks returns a boolean if a field has been set.
func (o *CampaignClicksData) HasTotalClicks() bool {
	if o != nil && o.TotalClicks != nil {
		return true
	}

	return false
}

// SetTotalClicks gets a reference to the given int32 and assigns it to the TotalClicks field.
func (o *CampaignClicksData) SetTotalClicks(v int32) {
	o.TotalClicks = &v
}

// GetGuid returns the Guid field value if set, zero value otherwise.
func (o *CampaignClicksData) GetGuid() string {
	if o == nil || o.Guid == nil {
		var ret string
		return ret
	}
	return *o.Guid
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignClicksData) GetGuidOk() (*string, bool) {
	if o == nil || o.Guid == nil {
		return nil, false
	}
	return o.Guid, true
}

// HasGuid returns a boolean if a field has been set.
func (o *CampaignClicksData) HasGuid() bool {
	if o != nil && o.Guid != nil {
		return true
	}

	return false
}

// SetGuid gets a reference to the given string and assigns it to the Guid field.
func (o *CampaignClicksData) SetGuid(v string) {
	o.Guid = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CampaignClicksData) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignClicksData) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CampaignClicksData) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CampaignClicksData) SetName(v string) {
	o.Name = &v
}

func (o CampaignClicksData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedTs != nil {
		toSerialize["created_ts"] = o.CreatedTs
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.BrandGuid != nil {
		toSerialize["brand_guid"] = o.BrandGuid
	}
	if o.CampaignChannels != nil {
		toSerialize["campaign_channels"] = o.CampaignChannels
	}
	if o.CreatedBy != nil {
		toSerialize["created_by"] = o.CreatedBy
	}
	if o.ModifiedTs != nil {
		toSerialize["modified_ts"] = o.ModifiedTs
	}
	if o.TotalClicks != nil {
		toSerialize["total_clicks"] = o.TotalClicks
	}
	if o.Guid != nil {
		toSerialize["guid"] = o.Guid
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableCampaignClicksData struct {
	value *CampaignClicksData
	isSet bool
}

func (v NullableCampaignClicksData) Get() *CampaignClicksData {
	return v.value
}

func (v *NullableCampaignClicksData) Set(val *CampaignClicksData) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignClicksData) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignClicksData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignClicksData(val *CampaignClicksData) *NullableCampaignClicksData {
	return &NullableCampaignClicksData{value: val, isSet: true}
}

func (v NullableCampaignClicksData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignClicksData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
