/*
Bitly API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.0
Contact: api@bitly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SortedLinks struct for SortedLinks
type SortedLinks struct {
	SortedLinks *[]ClickLink   `json:"sorted_links,omitempty"`
	Links       *[]BitlinkBody `json:"links,omitempty"`
}

// NewSortedLinks instantiates a new SortedLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSortedLinks() *SortedLinks {
	this := SortedLinks{}
	return &this
}

// NewSortedLinksWithDefaults instantiates a new SortedLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSortedLinksWithDefaults() *SortedLinks {
	this := SortedLinks{}
	return &this
}

// GetSortedLinks returns the SortedLinks field value if set, zero value otherwise.
func (o *SortedLinks) GetSortedLinks() []ClickLink {
	if o == nil || o.SortedLinks == nil {
		var ret []ClickLink
		return ret
	}
	return *o.SortedLinks
}

// GetSortedLinksOk returns a tuple with the SortedLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SortedLinks) GetSortedLinksOk() (*[]ClickLink, bool) {
	if o == nil || o.SortedLinks == nil {
		return nil, false
	}
	return o.SortedLinks, true
}

// HasSortedLinks returns a boolean if a field has been set.
func (o *SortedLinks) HasSortedLinks() bool {
	if o != nil && o.SortedLinks != nil {
		return true
	}

	return false
}

// SetSortedLinks gets a reference to the given []ClickLink and assigns it to the SortedLinks field.
func (o *SortedLinks) SetSortedLinks(v []ClickLink) {
	o.SortedLinks = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *SortedLinks) GetLinks() []BitlinkBody {
	if o == nil || o.Links == nil {
		var ret []BitlinkBody
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SortedLinks) GetLinksOk() (*[]BitlinkBody, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *SortedLinks) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []BitlinkBody and assigns it to the Links field.
func (o *SortedLinks) SetLinks(v []BitlinkBody) {
	o.Links = &v
}

func (o SortedLinks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.SortedLinks != nil {
		toSerialize["sorted_links"] = o.SortedLinks
	}
	if o.Links != nil {
		toSerialize["links"] = o.Links
	}
	return json.Marshal(toSerialize)
}

type NullableSortedLinks struct {
	value *SortedLinks
	isSet bool
}

func (v NullableSortedLinks) Get() *SortedLinks {
	return v.value
}

func (v *NullableSortedLinks) Set(val *SortedLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableSortedLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableSortedLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSortedLinks(val *SortedLinks) *NullableSortedLinks {
	return &NullableSortedLinks{value: val, isSet: true}
}

func (v NullableSortedLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSortedLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
