/*
Bitly API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.0
Contact: api@bitly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ClicksSummary struct for ClicksSummary
type ClicksSummary struct {
	Units         *int32  `json:"units,omitempty"`
	Unit          *string `json:"unit,omitempty"`
	TotalClicks   *int32  `json:"total_clicks,omitempty"`
	UnitReference *string `json:"unit_reference,omitempty"`
}

// NewClicksSummary instantiates a new ClicksSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClicksSummary() *ClicksSummary {
	this := ClicksSummary{}
	return &this
}

// NewClicksSummaryWithDefaults instantiates a new ClicksSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClicksSummaryWithDefaults() *ClicksSummary {
	this := ClicksSummary{}
	return &this
}

// GetUnits returns the Units field value if set, zero value otherwise.
func (o *ClicksSummary) GetUnits() int32 {
	if o == nil || o.Units == nil {
		var ret int32
		return ret
	}
	return *o.Units
}

// GetUnitsOk returns a tuple with the Units field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClicksSummary) GetUnitsOk() (*int32, bool) {
	if o == nil || o.Units == nil {
		return nil, false
	}
	return o.Units, true
}

// HasUnits returns a boolean if a field has been set.
func (o *ClicksSummary) HasUnits() bool {
	if o != nil && o.Units != nil {
		return true
	}

	return false
}

// SetUnits gets a reference to the given int32 and assigns it to the Units field.
func (o *ClicksSummary) SetUnits(v int32) {
	o.Units = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *ClicksSummary) GetUnit() string {
	if o == nil || o.Unit == nil {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClicksSummary) GetUnitOk() (*string, bool) {
	if o == nil || o.Unit == nil {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *ClicksSummary) HasUnit() bool {
	if o != nil && o.Unit != nil {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *ClicksSummary) SetUnit(v string) {
	o.Unit = &v
}

// GetTotalClicks returns the TotalClicks field value if set, zero value otherwise.
func (o *ClicksSummary) GetTotalClicks() int32 {
	if o == nil || o.TotalClicks == nil {
		var ret int32
		return ret
	}
	return *o.TotalClicks
}

// GetTotalClicksOk returns a tuple with the TotalClicks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClicksSummary) GetTotalClicksOk() (*int32, bool) {
	if o == nil || o.TotalClicks == nil {
		return nil, false
	}
	return o.TotalClicks, true
}

// HasTotalClicks returns a boolean if a field has been set.
func (o *ClicksSummary) HasTotalClicks() bool {
	if o != nil && o.TotalClicks != nil {
		return true
	}

	return false
}

// SetTotalClicks gets a reference to the given int32 and assigns it to the TotalClicks field.
func (o *ClicksSummary) SetTotalClicks(v int32) {
	o.TotalClicks = &v
}

// GetUnitReference returns the UnitReference field value if set, zero value otherwise.
func (o *ClicksSummary) GetUnitReference() string {
	if o == nil || o.UnitReference == nil {
		var ret string
		return ret
	}
	return *o.UnitReference
}

// GetUnitReferenceOk returns a tuple with the UnitReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClicksSummary) GetUnitReferenceOk() (*string, bool) {
	if o == nil || o.UnitReference == nil {
		return nil, false
	}
	return o.UnitReference, true
}

// HasUnitReference returns a boolean if a field has been set.
func (o *ClicksSummary) HasUnitReference() bool {
	if o != nil && o.UnitReference != nil {
		return true
	}

	return false
}

// SetUnitReference gets a reference to the given string and assigns it to the UnitReference field.
func (o *ClicksSummary) SetUnitReference(v string) {
	o.UnitReference = &v
}

func (o ClicksSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Units != nil {
		toSerialize["units"] = o.Units
	}
	if o.Unit != nil {
		toSerialize["unit"] = o.Unit
	}
	if o.TotalClicks != nil {
		toSerialize["total_clicks"] = o.TotalClicks
	}
	if o.UnitReference != nil {
		toSerialize["unit_reference"] = o.UnitReference
	}
	return json.Marshal(toSerialize)
}

type NullableClicksSummary struct {
	value *ClicksSummary
	isSet bool
}

func (v NullableClicksSummary) Get() *ClicksSummary {
	return v.value
}

func (v *NullableClicksSummary) Set(val *ClicksSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableClicksSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableClicksSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClicksSummary(val *ClicksSummary) *NullableClicksSummary {
	return &NullableClicksSummary{value: val, isSet: true}
}

func (v NullableClicksSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClicksSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
