/*
Bitly API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.0
Contact: api@bitly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// BillingDowngrade struct for BillingDowngrade
type BillingDowngrade struct {
	GroupGuids *[]string `json:"group_guids,omitempty"`
	TierName   *string   `json:"tier_name,omitempty"`
}

// NewBillingDowngrade instantiates a new BillingDowngrade object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingDowngrade() *BillingDowngrade {
	this := BillingDowngrade{}
	return &this
}

// NewBillingDowngradeWithDefaults instantiates a new BillingDowngrade object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingDowngradeWithDefaults() *BillingDowngrade {
	this := BillingDowngrade{}
	return &this
}

// GetGroupGuids returns the GroupGuids field value if set, zero value otherwise.
func (o *BillingDowngrade) GetGroupGuids() []string {
	if o == nil || o.GroupGuids == nil {
		var ret []string
		return ret
	}
	return *o.GroupGuids
}

// GetGroupGuidsOk returns a tuple with the GroupGuids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingDowngrade) GetGroupGuidsOk() (*[]string, bool) {
	if o == nil || o.GroupGuids == nil {
		return nil, false
	}
	return o.GroupGuids, true
}

// HasGroupGuids returns a boolean if a field has been set.
func (o *BillingDowngrade) HasGroupGuids() bool {
	if o != nil && o.GroupGuids != nil {
		return true
	}

	return false
}

// SetGroupGuids gets a reference to the given []string and assigns it to the GroupGuids field.
func (o *BillingDowngrade) SetGroupGuids(v []string) {
	o.GroupGuids = &v
}

// GetTierName returns the TierName field value if set, zero value otherwise.
func (o *BillingDowngrade) GetTierName() string {
	if o == nil || o.TierName == nil {
		var ret string
		return ret
	}
	return *o.TierName
}

// GetTierNameOk returns a tuple with the TierName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingDowngrade) GetTierNameOk() (*string, bool) {
	if o == nil || o.TierName == nil {
		return nil, false
	}
	return o.TierName, true
}

// HasTierName returns a boolean if a field has been set.
func (o *BillingDowngrade) HasTierName() bool {
	if o != nil && o.TierName != nil {
		return true
	}

	return false
}

// SetTierName gets a reference to the given string and assigns it to the TierName field.
func (o *BillingDowngrade) SetTierName(v string) {
	o.TierName = &v
}

func (o BillingDowngrade) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.GroupGuids != nil {
		toSerialize["group_guids"] = o.GroupGuids
	}
	if o.TierName != nil {
		toSerialize["tier_name"] = o.TierName
	}
	return json.Marshal(toSerialize)
}

type NullableBillingDowngrade struct {
	value *BillingDowngrade
	isSet bool
}

func (v NullableBillingDowngrade) Get() *BillingDowngrade {
	return v.value
}

func (v *NullableBillingDowngrade) Set(val *BillingDowngrade) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingDowngrade) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingDowngrade) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingDowngrade(val *BillingDowngrade) *NullableBillingDowngrade {
	return &NullableBillingDowngrade{value: val, isSet: true}
}

func (v NullableBillingDowngrade) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingDowngrade) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
