/*
Bitly API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.0
Contact: api@bitly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CampaignChannelClicks struct for CampaignChannelClicks
type CampaignChannelClicks struct {
	CreatedTs       *int32               `json:"created_ts,omitempty"`
	ChannelGuid     *string              `json:"channel_guid,omitempty"`
	TotalClicks     *int32               `json:"total_clicks,omitempty"`
	ChannelName     *string              `json:"channel_name,omitempty"`
	CampaignGuid    *string              `json:"campaign_guid,omitempty"`
	ChannelBitlinks *ChannelBitlinks     `json:"channel_bitlinks,omitempty"`
	Clicks          *[]CampaignClickData `json:"clicks,omitempty"`
}

// NewCampaignChannelClicks instantiates a new CampaignChannelClicks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignChannelClicks() *CampaignChannelClicks {
	this := CampaignChannelClicks{}
	return &this
}

// NewCampaignChannelClicksWithDefaults instantiates a new CampaignChannelClicks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignChannelClicksWithDefaults() *CampaignChannelClicks {
	this := CampaignChannelClicks{}
	return &this
}

// GetCreatedTs returns the CreatedTs field value if set, zero value otherwise.
func (o *CampaignChannelClicks) GetCreatedTs() int32 {
	if o == nil || o.CreatedTs == nil {
		var ret int32
		return ret
	}
	return *o.CreatedTs
}

// GetCreatedTsOk returns a tuple with the CreatedTs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignChannelClicks) GetCreatedTsOk() (*int32, bool) {
	if o == nil || o.CreatedTs == nil {
		return nil, false
	}
	return o.CreatedTs, true
}

// HasCreatedTs returns a boolean if a field has been set.
func (o *CampaignChannelClicks) HasCreatedTs() bool {
	if o != nil && o.CreatedTs != nil {
		return true
	}

	return false
}

// SetCreatedTs gets a reference to the given int32 and assigns it to the CreatedTs field.
func (o *CampaignChannelClicks) SetCreatedTs(v int32) {
	o.CreatedTs = &v
}

// GetChannelGuid returns the ChannelGuid field value if set, zero value otherwise.
func (o *CampaignChannelClicks) GetChannelGuid() string {
	if o == nil || o.ChannelGuid == nil {
		var ret string
		return ret
	}
	return *o.ChannelGuid
}

// GetChannelGuidOk returns a tuple with the ChannelGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignChannelClicks) GetChannelGuidOk() (*string, bool) {
	if o == nil || o.ChannelGuid == nil {
		return nil, false
	}
	return o.ChannelGuid, true
}

// HasChannelGuid returns a boolean if a field has been set.
func (o *CampaignChannelClicks) HasChannelGuid() bool {
	if o != nil && o.ChannelGuid != nil {
		return true
	}

	return false
}

// SetChannelGuid gets a reference to the given string and assigns it to the ChannelGuid field.
func (o *CampaignChannelClicks) SetChannelGuid(v string) {
	o.ChannelGuid = &v
}

// GetTotalClicks returns the TotalClicks field value if set, zero value otherwise.
func (o *CampaignChannelClicks) GetTotalClicks() int32 {
	if o == nil || o.TotalClicks == nil {
		var ret int32
		return ret
	}
	return *o.TotalClicks
}

// GetTotalClicksOk returns a tuple with the TotalClicks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignChannelClicks) GetTotalClicksOk() (*int32, bool) {
	if o == nil || o.TotalClicks == nil {
		return nil, false
	}
	return o.TotalClicks, true
}

// HasTotalClicks returns a boolean if a field has been set.
func (o *CampaignChannelClicks) HasTotalClicks() bool {
	if o != nil && o.TotalClicks != nil {
		return true
	}

	return false
}

// SetTotalClicks gets a reference to the given int32 and assigns it to the TotalClicks field.
func (o *CampaignChannelClicks) SetTotalClicks(v int32) {
	o.TotalClicks = &v
}

// GetChannelName returns the ChannelName field value if set, zero value otherwise.
func (o *CampaignChannelClicks) GetChannelName() string {
	if o == nil || o.ChannelName == nil {
		var ret string
		return ret
	}
	return *o.ChannelName
}

// GetChannelNameOk returns a tuple with the ChannelName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignChannelClicks) GetChannelNameOk() (*string, bool) {
	if o == nil || o.ChannelName == nil {
		return nil, false
	}
	return o.ChannelName, true
}

// HasChannelName returns a boolean if a field has been set.
func (o *CampaignChannelClicks) HasChannelName() bool {
	if o != nil && o.ChannelName != nil {
		return true
	}

	return false
}

// SetChannelName gets a reference to the given string and assigns it to the ChannelName field.
func (o *CampaignChannelClicks) SetChannelName(v string) {
	o.ChannelName = &v
}

// GetCampaignGuid returns the CampaignGuid field value if set, zero value otherwise.
func (o *CampaignChannelClicks) GetCampaignGuid() string {
	if o == nil || o.CampaignGuid == nil {
		var ret string
		return ret
	}
	return *o.CampaignGuid
}

// GetCampaignGuidOk returns a tuple with the CampaignGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignChannelClicks) GetCampaignGuidOk() (*string, bool) {
	if o == nil || o.CampaignGuid == nil {
		return nil, false
	}
	return o.CampaignGuid, true
}

// HasCampaignGuid returns a boolean if a field has been set.
func (o *CampaignChannelClicks) HasCampaignGuid() bool {
	if o != nil && o.CampaignGuid != nil {
		return true
	}

	return false
}

// SetCampaignGuid gets a reference to the given string and assigns it to the CampaignGuid field.
func (o *CampaignChannelClicks) SetCampaignGuid(v string) {
	o.CampaignGuid = &v
}

// GetChannelBitlinks returns the ChannelBitlinks field value if set, zero value otherwise.
func (o *CampaignChannelClicks) GetChannelBitlinks() ChannelBitlinks {
	if o == nil || o.ChannelBitlinks == nil {
		var ret ChannelBitlinks
		return ret
	}
	return *o.ChannelBitlinks
}

// GetChannelBitlinksOk returns a tuple with the ChannelBitlinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignChannelClicks) GetChannelBitlinksOk() (*ChannelBitlinks, bool) {
	if o == nil || o.ChannelBitlinks == nil {
		return nil, false
	}
	return o.ChannelBitlinks, true
}

// HasChannelBitlinks returns a boolean if a field has been set.
func (o *CampaignChannelClicks) HasChannelBitlinks() bool {
	if o != nil && o.ChannelBitlinks != nil {
		return true
	}

	return false
}

// SetChannelBitlinks gets a reference to the given ChannelBitlinks and assigns it to the ChannelBitlinks field.
func (o *CampaignChannelClicks) SetChannelBitlinks(v ChannelBitlinks) {
	o.ChannelBitlinks = &v
}

// GetClicks returns the Clicks field value if set, zero value otherwise.
func (o *CampaignChannelClicks) GetClicks() []CampaignClickData {
	if o == nil || o.Clicks == nil {
		var ret []CampaignClickData
		return ret
	}
	return *o.Clicks
}

// GetClicksOk returns a tuple with the Clicks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignChannelClicks) GetClicksOk() (*[]CampaignClickData, bool) {
	if o == nil || o.Clicks == nil {
		return nil, false
	}
	return o.Clicks, true
}

// HasClicks returns a boolean if a field has been set.
func (o *CampaignChannelClicks) HasClicks() bool {
	if o != nil && o.Clicks != nil {
		return true
	}

	return false
}

// SetClicks gets a reference to the given []CampaignClickData and assigns it to the Clicks field.
func (o *CampaignChannelClicks) SetClicks(v []CampaignClickData) {
	o.Clicks = &v
}

func (o CampaignChannelClicks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedTs != nil {
		toSerialize["created_ts"] = o.CreatedTs
	}
	if o.ChannelGuid != nil {
		toSerialize["channel_guid"] = o.ChannelGuid
	}
	if o.TotalClicks != nil {
		toSerialize["total_clicks"] = o.TotalClicks
	}
	if o.ChannelName != nil {
		toSerialize["channel_name"] = o.ChannelName
	}
	if o.CampaignGuid != nil {
		toSerialize["campaign_guid"] = o.CampaignGuid
	}
	if o.ChannelBitlinks != nil {
		toSerialize["channel_bitlinks"] = o.ChannelBitlinks
	}
	if o.Clicks != nil {
		toSerialize["clicks"] = o.Clicks
	}
	return json.Marshal(toSerialize)
}

type NullableCampaignChannelClicks struct {
	value *CampaignChannelClicks
	isSet bool
}

func (v NullableCampaignChannelClicks) Get() *CampaignChannelClicks {
	return v.value
}

func (v *NullableCampaignChannelClicks) Set(val *CampaignChannelClicks) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignChannelClicks) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignChannelClicks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignChannelClicks(val *CampaignChannelClicks) *NullableCampaignChannelClicks {
	return &NullableCampaignChannelClicks{value: val, isSet: true}
}

func (v NullableCampaignChannelClicks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignChannelClicks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
