/*
Bitly API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.0
Contact: api@bitly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GroupClicksByFacet struct for GroupClicksByFacet
type GroupClicksByFacet struct {
	Units         *int32            `json:"units,omitempty"`
	Data          *[]FacetCountData `json:"data,omitempty"`
	UnitReference *string           `json:"unit_reference,omitempty"`
	Unit          *string           `json:"unit,omitempty"`
}

// NewGroupClicksByFacet instantiates a new GroupClicksByFacet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupClicksByFacet() *GroupClicksByFacet {
	this := GroupClicksByFacet{}
	return &this
}

// NewGroupClicksByFacetWithDefaults instantiates a new GroupClicksByFacet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupClicksByFacetWithDefaults() *GroupClicksByFacet {
	this := GroupClicksByFacet{}
	return &this
}

// GetUnits returns the Units field value if set, zero value otherwise.
func (o *GroupClicksByFacet) GetUnits() int32 {
	if o == nil || o.Units == nil {
		var ret int32
		return ret
	}
	return *o.Units
}

// GetUnitsOk returns a tuple with the Units field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupClicksByFacet) GetUnitsOk() (*int32, bool) {
	if o == nil || o.Units == nil {
		return nil, false
	}
	return o.Units, true
}

// HasUnits returns a boolean if a field has been set.
func (o *GroupClicksByFacet) HasUnits() bool {
	if o != nil && o.Units != nil {
		return true
	}

	return false
}

// SetUnits gets a reference to the given int32 and assigns it to the Units field.
func (o *GroupClicksByFacet) SetUnits(v int32) {
	o.Units = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GroupClicksByFacet) GetData() []FacetCountData {
	if o == nil || o.Data == nil {
		var ret []FacetCountData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupClicksByFacet) GetDataOk() (*[]FacetCountData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GroupClicksByFacet) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []FacetCountData and assigns it to the Data field.
func (o *GroupClicksByFacet) SetData(v []FacetCountData) {
	o.Data = &v
}

// GetUnitReference returns the UnitReference field value if set, zero value otherwise.
func (o *GroupClicksByFacet) GetUnitReference() string {
	if o == nil || o.UnitReference == nil {
		var ret string
		return ret
	}
	return *o.UnitReference
}

// GetUnitReferenceOk returns a tuple with the UnitReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupClicksByFacet) GetUnitReferenceOk() (*string, bool) {
	if o == nil || o.UnitReference == nil {
		return nil, false
	}
	return o.UnitReference, true
}

// HasUnitReference returns a boolean if a field has been set.
func (o *GroupClicksByFacet) HasUnitReference() bool {
	if o != nil && o.UnitReference != nil {
		return true
	}

	return false
}

// SetUnitReference gets a reference to the given string and assigns it to the UnitReference field.
func (o *GroupClicksByFacet) SetUnitReference(v string) {
	o.UnitReference = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *GroupClicksByFacet) GetUnit() string {
	if o == nil || o.Unit == nil {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupClicksByFacet) GetUnitOk() (*string, bool) {
	if o == nil || o.Unit == nil {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *GroupClicksByFacet) HasUnit() bool {
	if o != nil && o.Unit != nil {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *GroupClicksByFacet) SetUnit(v string) {
	o.Unit = &v
}

func (o GroupClicksByFacet) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Units != nil {
		toSerialize["units"] = o.Units
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.UnitReference != nil {
		toSerialize["unit_reference"] = o.UnitReference
	}
	if o.Unit != nil {
		toSerialize["unit"] = o.Unit
	}
	return json.Marshal(toSerialize)
}

type NullableGroupClicksByFacet struct {
	value *GroupClicksByFacet
	isSet bool
}

func (v NullableGroupClicksByFacet) Get() *GroupClicksByFacet {
	return v.value
}

func (v *NullableGroupClicksByFacet) Set(val *GroupClicksByFacet) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupClicksByFacet) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupClicksByFacet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupClicksByFacet(val *GroupClicksByFacet) *NullableGroupClicksByFacet {
	return &NullableGroupClicksByFacet{value: val, isSet: true}
}

func (v NullableGroupClicksByFacet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupClicksByFacet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
