/*
Bitly API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.0
Contact: api@bitly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UserPreferences struct for UserPreferences
type UserPreferences struct {
	Preferences *[]UserPreference `json:"preferences,omitempty"`
}

// NewUserPreferences instantiates a new UserPreferences object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserPreferences() *UserPreferences {
	this := UserPreferences{}
	return &this
}

// NewUserPreferencesWithDefaults instantiates a new UserPreferences object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserPreferencesWithDefaults() *UserPreferences {
	this := UserPreferences{}
	return &this
}

// GetPreferences returns the Preferences field value if set, zero value otherwise.
func (o *UserPreferences) GetPreferences() []UserPreference {
	if o == nil || o.Preferences == nil {
		var ret []UserPreference
		return ret
	}
	return *o.Preferences
}

// GetPreferencesOk returns a tuple with the Preferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserPreferences) GetPreferencesOk() (*[]UserPreference, bool) {
	if o == nil || o.Preferences == nil {
		return nil, false
	}
	return o.Preferences, true
}

// HasPreferences returns a boolean if a field has been set.
func (o *UserPreferences) HasPreferences() bool {
	if o != nil && o.Preferences != nil {
		return true
	}

	return false
}

// SetPreferences gets a reference to the given []UserPreference and assigns it to the Preferences field.
func (o *UserPreferences) SetPreferences(v []UserPreference) {
	o.Preferences = &v
}

func (o UserPreferences) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Preferences != nil {
		toSerialize["preferences"] = o.Preferences
	}
	return json.Marshal(toSerialize)
}

type NullableUserPreferences struct {
	value *UserPreferences
	isSet bool
}

func (v NullableUserPreferences) Get() *UserPreferences {
	return v.value
}

func (v *NullableUserPreferences) Set(val *UserPreferences) {
	v.value = val
	v.isSet = true
}

func (v NullableUserPreferences) IsSet() bool {
	return v.isSet
}

func (v *NullableUserPreferences) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserPreferences(val *UserPreferences) *NullableUserPreferences {
	return &NullableUserPreferences{value: val, isSet: true}
}

func (v NullableUserPreferences) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserPreferences) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
