/*
Bitly API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.0
Contact: api@bitly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UpdateOverrideRules struct for UpdateOverrideRules
type UpdateOverrideRules struct {
	Rules *string `json:"rules,omitempty"`
}

// NewUpdateOverrideRules instantiates a new UpdateOverrideRules object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOverrideRules() *UpdateOverrideRules {
	this := UpdateOverrideRules{}
	return &this
}

// NewUpdateOverrideRulesWithDefaults instantiates a new UpdateOverrideRules object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOverrideRulesWithDefaults() *UpdateOverrideRules {
	this := UpdateOverrideRules{}
	return &this
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *UpdateOverrideRules) GetRules() string {
	if o == nil || o.Rules == nil {
		var ret string
		return ret
	}
	return *o.Rules
}

// GetRulesOk returns a tuple with the Rules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOverrideRules) GetRulesOk() (*string, bool) {
	if o == nil || o.Rules == nil {
		return nil, false
	}
	return o.Rules, true
}

// HasRules returns a boolean if a field has been set.
func (o *UpdateOverrideRules) HasRules() bool {
	if o != nil && o.Rules != nil {
		return true
	}

	return false
}

// SetRules gets a reference to the given string and assigns it to the Rules field.
func (o *UpdateOverrideRules) SetRules(v string) {
	o.Rules = &v
}

func (o UpdateOverrideRules) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Rules != nil {
		toSerialize["rules"] = o.Rules
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateOverrideRules struct {
	value *UpdateOverrideRules
	isSet bool
}

func (v NullableUpdateOverrideRules) Get() *UpdateOverrideRules {
	return v.value
}

func (v *NullableUpdateOverrideRules) Set(val *UpdateOverrideRules) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOverrideRules) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOverrideRules) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOverrideRules(val *UpdateOverrideRules) *NullableUpdateOverrideRules {
	return &NullableUpdateOverrideRules{value: val, isSet: true}
}

func (v NullableUpdateOverrideRules) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOverrideRules) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
