/*
Bitly API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.0
Contact: api@bitly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PlanLimitsAllOf struct for PlanLimitsAllOf
type PlanLimitsAllOf struct {
	OrganizationGuid *string      `json:"organization_guid,omitempty"`
	PlanLimits       *[]PlanLimit `json:"plan_limits,omitempty"`
}

// NewPlanLimitsAllOf instantiates a new PlanLimitsAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanLimitsAllOf() *PlanLimitsAllOf {
	this := PlanLimitsAllOf{}
	return &this
}

// NewPlanLimitsAllOfWithDefaults instantiates a new PlanLimitsAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanLimitsAllOfWithDefaults() *PlanLimitsAllOf {
	this := PlanLimitsAllOf{}
	return &this
}

// GetOrganizationGuid returns the OrganizationGuid field value if set, zero value otherwise.
func (o *PlanLimitsAllOf) GetOrganizationGuid() string {
	if o == nil || o.OrganizationGuid == nil {
		var ret string
		return ret
	}
	return *o.OrganizationGuid
}

// GetOrganizationGuidOk returns a tuple with the OrganizationGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanLimitsAllOf) GetOrganizationGuidOk() (*string, bool) {
	if o == nil || o.OrganizationGuid == nil {
		return nil, false
	}
	return o.OrganizationGuid, true
}

// HasOrganizationGuid returns a boolean if a field has been set.
func (o *PlanLimitsAllOf) HasOrganizationGuid() bool {
	if o != nil && o.OrganizationGuid != nil {
		return true
	}

	return false
}

// SetOrganizationGuid gets a reference to the given string and assigns it to the OrganizationGuid field.
func (o *PlanLimitsAllOf) SetOrganizationGuid(v string) {
	o.OrganizationGuid = &v
}

// GetPlanLimits returns the PlanLimits field value if set, zero value otherwise.
func (o *PlanLimitsAllOf) GetPlanLimits() []PlanLimit {
	if o == nil || o.PlanLimits == nil {
		var ret []PlanLimit
		return ret
	}
	return *o.PlanLimits
}

// GetPlanLimitsOk returns a tuple with the PlanLimits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanLimitsAllOf) GetPlanLimitsOk() (*[]PlanLimit, bool) {
	if o == nil || o.PlanLimits == nil {
		return nil, false
	}
	return o.PlanLimits, true
}

// HasPlanLimits returns a boolean if a field has been set.
func (o *PlanLimitsAllOf) HasPlanLimits() bool {
	if o != nil && o.PlanLimits != nil {
		return true
	}

	return false
}

// SetPlanLimits gets a reference to the given []PlanLimit and assigns it to the PlanLimits field.
func (o *PlanLimitsAllOf) SetPlanLimits(v []PlanLimit) {
	o.PlanLimits = &v
}

func (o PlanLimitsAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.OrganizationGuid != nil {
		toSerialize["organization_guid"] = o.OrganizationGuid
	}
	if o.PlanLimits != nil {
		toSerialize["plan_limits"] = o.PlanLimits
	}
	return json.Marshal(toSerialize)
}

type NullablePlanLimitsAllOf struct {
	value *PlanLimitsAllOf
	isSet bool
}

func (v NullablePlanLimitsAllOf) Get() *PlanLimitsAllOf {
	return v.value
}

func (v *NullablePlanLimitsAllOf) Set(val *PlanLimitsAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanLimitsAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanLimitsAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanLimitsAllOf(val *PlanLimitsAllOf) *NullablePlanLimitsAllOf {
	return &NullablePlanLimitsAllOf{value: val, isSet: true}
}

func (v NullablePlanLimitsAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanLimitsAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
