/*
Bitly API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.0
Contact: api@bitly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ChannelModify struct for ChannelModify
type ChannelModify struct {
	GroupGuid *string `json:"group_guid,omitempty"`
	Guid      *string `json:"guid,omitempty"`
	Name      *string `json:"name,omitempty"`
	// ISO_TIMESTAMP
	Modified *string `json:"modified,omitempty"`
	// ISO TIMESTAMP
	Created  *string               `json:"created,omitempty"`
	Bitlinks *[]BaseChannelBitlink `json:"bitlinks,omitempty"`
}

// NewChannelModify instantiates a new ChannelModify object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelModify() *ChannelModify {
	this := ChannelModify{}
	return &this
}

// NewChannelModifyWithDefaults instantiates a new ChannelModify object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelModifyWithDefaults() *ChannelModify {
	this := ChannelModify{}
	return &this
}

// GetGroupGuid returns the GroupGuid field value if set, zero value otherwise.
func (o *ChannelModify) GetGroupGuid() string {
	if o == nil || o.GroupGuid == nil {
		var ret string
		return ret
	}
	return *o.GroupGuid
}

// GetGroupGuidOk returns a tuple with the GroupGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelModify) GetGroupGuidOk() (*string, bool) {
	if o == nil || o.GroupGuid == nil {
		return nil, false
	}
	return o.GroupGuid, true
}

// HasGroupGuid returns a boolean if a field has been set.
func (o *ChannelModify) HasGroupGuid() bool {
	if o != nil && o.GroupGuid != nil {
		return true
	}

	return false
}

// SetGroupGuid gets a reference to the given string and assigns it to the GroupGuid field.
func (o *ChannelModify) SetGroupGuid(v string) {
	o.GroupGuid = &v
}

// GetGuid returns the Guid field value if set, zero value otherwise.
func (o *ChannelModify) GetGuid() string {
	if o == nil || o.Guid == nil {
		var ret string
		return ret
	}
	return *o.Guid
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelModify) GetGuidOk() (*string, bool) {
	if o == nil || o.Guid == nil {
		return nil, false
	}
	return o.Guid, true
}

// HasGuid returns a boolean if a field has been set.
func (o *ChannelModify) HasGuid() bool {
	if o != nil && o.Guid != nil {
		return true
	}

	return false
}

// SetGuid gets a reference to the given string and assigns it to the Guid field.
func (o *ChannelModify) SetGuid(v string) {
	o.Guid = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ChannelModify) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelModify) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ChannelModify) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ChannelModify) SetName(v string) {
	o.Name = &v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *ChannelModify) GetModified() string {
	if o == nil || o.Modified == nil {
		var ret string
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelModify) GetModifiedOk() (*string, bool) {
	if o == nil || o.Modified == nil {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *ChannelModify) HasModified() bool {
	if o != nil && o.Modified != nil {
		return true
	}

	return false
}

// SetModified gets a reference to the given string and assigns it to the Modified field.
func (o *ChannelModify) SetModified(v string) {
	o.Modified = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *ChannelModify) GetCreated() string {
	if o == nil || o.Created == nil {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelModify) GetCreatedOk() (*string, bool) {
	if o == nil || o.Created == nil {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *ChannelModify) HasCreated() bool {
	if o != nil && o.Created != nil {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *ChannelModify) SetCreated(v string) {
	o.Created = &v
}

// GetBitlinks returns the Bitlinks field value if set, zero value otherwise.
func (o *ChannelModify) GetBitlinks() []BaseChannelBitlink {
	if o == nil || o.Bitlinks == nil {
		var ret []BaseChannelBitlink
		return ret
	}
	return *o.Bitlinks
}

// GetBitlinksOk returns a tuple with the Bitlinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelModify) GetBitlinksOk() (*[]BaseChannelBitlink, bool) {
	if o == nil || o.Bitlinks == nil {
		return nil, false
	}
	return o.Bitlinks, true
}

// HasBitlinks returns a boolean if a field has been set.
func (o *ChannelModify) HasBitlinks() bool {
	if o != nil && o.Bitlinks != nil {
		return true
	}

	return false
}

// SetBitlinks gets a reference to the given []BaseChannelBitlink and assigns it to the Bitlinks field.
func (o *ChannelModify) SetBitlinks(v []BaseChannelBitlink) {
	o.Bitlinks = &v
}

func (o ChannelModify) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.GroupGuid != nil {
		toSerialize["group_guid"] = o.GroupGuid
	}
	if o.Guid != nil {
		toSerialize["guid"] = o.Guid
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Modified != nil {
		toSerialize["modified"] = o.Modified
	}
	if o.Created != nil {
		toSerialize["created"] = o.Created
	}
	if o.Bitlinks != nil {
		toSerialize["bitlinks"] = o.Bitlinks
	}
	return json.Marshal(toSerialize)
}

type NullableChannelModify struct {
	value *ChannelModify
	isSet bool
}

func (v NullableChannelModify) Get() *ChannelModify {
	return v.value
}

func (v *NullableChannelModify) Set(val *ChannelModify) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelModify) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelModify) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelModify(val *ChannelModify) *NullableChannelModify {
	return &NullableChannelModify{value: val, isSet: true}
}

func (v NullableChannelModify) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelModify) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
